### ISSUE TITLE
Add support for collapsing tables

### ISSUE THREAD

**Issue by Broxzier** [Theodor-Lindberg/NPP-TOML-Syntax#6]
When you use "INI file" highlighting for TOML files, you have the ability to collapse a section. It would be nice if the same functionality would also work when using this syntax highlighter.

```toml
[table]
title = "Da Table"
description = "look at my table"
data = [ 1, 2, 3, 4, 5 ]

  [[table.settings]]
  name = "applejuice"
  age = 5

  [[table.settings]]
  name = "pearjuice"
  age = 25

  [[table.settings]]
  name = "bananajuice"
  age = 125
```

This is how it looks with INI file higlighting, and two groups collapsed:
![image](https://github.com/Theodor-Lindberg/NPP-TOML-Syntax/assets/9705046/dee0927e-13dd-451d-a178-ecfa37e60bb1)
